# Permalinks
permalink:           pretty

# Setup
title:               adam-gligor
tagline:             blog, knowledge, brain dump
url:                 http://adam-gligor.github.io
paginate:            5
baseurl:             ""
markdown:            kramdown

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:             Adam Gligor
  email:            gligor.adam@gmail.com
  twitter:          https://twitter.com/adamgligor
  github:           https://github.com/adam-gligor
  linkedin:         https://www.linkedin.com/in/adam-gligor



# Custom vars
version:             2.0.0
github:
  repo:             https://github.com/adam-gligor

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

pages_list:
  Blog: '/'
  About: '/about'
  Archive: '/archive'
